version: "3.8"

services:
  frontend:
    build: .
    restart: always
    networks:
      - redefrontend
    volumes:
      - frontendveiculos
    ports:
      - 3333:3000

volumes:
  frontendveiculos:

networks:
  redefrontend:
    driver: bridge
